### ISSUE TITLE
app.route blocks middleware mounted at a subpath

### ISSUE THREAD

**Issue by Lordfirespeed** [tinyhttp/tinyhttp#433] opened 2024-07-24 11:21 UTC
# Case 1
## To Reproduce
```ts
import { App } from '@tinyhttp/app'

const app = new App()

app.route('/')
  .get((req, res) => void res.send(`this is rooty`))

app.use('/foo', (req, res) => void res.send(`this is not rooty`))

app.listen(3000)
```

## Result
- [http://localhost:3000](http://localhost:3000) yields `this is rooty`
- [http://localhost:3000/foo](http://localhost:3000/foo) yields `Not Found`

## Expected behavior
- [http://localhost:3000](http://localhost:3000) yields `this is rooty`
- [http://localhost:3000/foo](http://localhost:3000/foo) yields `this is not rooty`

# Case 2 
## To Reproduce
```ts
import { App } from '@tinyhttp/app'

const app = new App()

app.use('/', (req, res) => void res.send(`this is rooty`))

app.use('/foo', (req, res) => void res.send(`this is not rooty`))

app.listen(3000)
```

## Result
- [http://localhost:3000](http://localhost:3000) yields `this is rooty`
- [http://localhost:3000/foo](http://localhost:3000/foo) yields `this is rooty`

## Expected behavior
- [http://localhost:3000](http://localhost:3000) yields `this is rooty`
- [http://localhost:3000/foo](http://localhost:3000/foo) yields `this is not rooty`

## Evironment

- `node`: 20.11.1
- `@tinyhttp/app`: 2.3.0

**Comment by Lordfirespeed** [comment] 2024-07-24 11:31
Part of the problem here is that the docs are contradictory.

- [here](https://tinyhttp.v1rtl.site/docs/main-concepts.html#route-paths) they claim `'/'` "will match requests to the root route".
- [here](https://tinyhttp.v1rtl.site/docs/main-concepts.html#path) they claim `'/'` "will handle all routes" and "[path argument] defaults to `'/'`"

**Comment by aarontravass** [comment] 2024-07-24 15:44
Hey @Lordfirespeed, thank you for raising this issue. I will look into it today evening.

**Comment by talentlessguy** [comment] 2024-07-24 19:09
the case 2 is the same as with express, that's not a bug:

```
λ curl localhost:3000/foo
this is rooty⏎                                        
λ curl localhost:3000
this is rooty⏎ 
```

```ts
import exoress from 'npm:express'

const app = polka()

app.use('/', (req, res) => void res.end(`this is rooty`))

app.use('/foo', (req, res) => void res.end(`this is not rooty`))

app.listen(3000)

```

**Comment by talentlessguy** [comment] 2024-07-24 19:13
Narrowed down the bug. The problem is not with `/` on middleware. It's the `app.route` who has the bug.

This for example works as expected:

```js
import {App} from 'npm:@tinyhttp/app'

const app = new App()

app.get('/', (req, res) => void res.end(`this is rooty`))

app.use('/foo', (req, res) => void res.end(`this is not rooty`))

app.listen(3000)
```

**Comment by aarontravass** [comment] 2024-07-25 05:10
I narrowed down the issue to subapps. In particular, the way subapps behave due to `/` being treated as `*`. 

Code to reproduce:
```ts
const app = new App()
const sub = new App()
app.use('/', sub)
app.use('/foo', (req, res) => res.end(req.url))
app.listen()
```

For this, I propose 2 solutions:
1. **Treat `/` as a regular route and `/*` as global (credit @Lordfirespeed)**: I am unsure if this would be a breaking change.
2. **Quit subapp execution if this condition is met `!res.writableEnded && idx >= mw.length`**: The problem happens because each subapp has its own `notFound` error handler set up and thus, even if the route exists in some other app, it will always return 404 since current execution does not quit the subapp.

**Comment by aarontravass** [comment] 2024-07-25 05:13
@talentlessguy let me know which one you prefer.

**Comment by talentlessguy** [comment] 2024-07-25 06:40
@aarontravass the second should be fixed. we shouldn't change behavior of tinyhttp to stay compatible with Express router.

**Comment by Lordfirespeed** [comment] 2024-07-25 12:56
> @aarontravass the second should be fixed. we shouldn't change behavior of tinyhttp to stay compatible with Express router.

I personally think `/` as a catch-all has never made any sense. 

Porting an app from Express already requires replacing all `Router` with `App`. Why not replacing `/` with `/*` ?

**Comment by aarontravass** [comment] 2024-07-25 16:10
> Why not replacing `/` with `/*` ?

I guess the ambiguity arises from express itself given that example 2 works as intended (`/` catches all routes) but example 1 does not because `app.route` uses a strict version of each path.

**Comment by Lordfirespeed** [comment] 2024-07-25 22:17
> I guess the ambiguity arises from express ...

Aye, exactly. I don't find it intuitive that `use` treats the path parameter differently to `route` and all the verb-specific methods, but that *is* what Express used to do.

**Comment by aarontravass** [comment] 2024-07-26 01:03
> > I guess the ambiguity arises from express ...
> 
> Aye, exactly. I don't find it intuitive that `use` treats the path parameter differently to `route` and all the verb-specific methods, but that _is_ what Express used to do.

tinyhttp is supposed to be a drop in replacement and thus, comes packaged with all the quirks of express. My gripe lies with the fact that a certain subset of users may have become accustomed to the usage of `/` and therefore a refactor, if they do decide to bump local versions, would be rather sedulous. 

In hindsight, we could fix this issue, bump tinyhttp to v3 and maybe release in the next couple of months.

**Comment by talentlessguy** [comment] 2024-07-26 05:31
the bugfix is not a breaking change, we don't need to wait next couple of months. Behaviour should be mirrored to express. "Compatible with Express" doesn't mean that all the imports are the same, it means that if you swap out express for tinyhttp it should just work. That's the goal. If there's a bug in th's behaviour, it should be fixed. tinyhttp doesn't aim to be a new great framework, it's goal is tinyhttp replacement, so we have to inherit many of the quirks express has

**Comment by Lordfirespeed** [comment] 2024-07-26 08:01
> the bugfix is not a breaking change

I think Aaron is referring to a refactor bringing the `use` path parameter in-line with `route` path parameter ?

**Comment by Lordfirespeed** [comment] 2024-07-27 23:06
The issue is actually more contrived; apps are actually not passing their `next` function to subapps, so it is impossible for matched subapps to notify their parents to continue middleware execution. 

I've opened #434 for review

**Closed** 2024-07-29 05:51 UTC
Labels: bug, core
