### ISSUE TITLE
Misleading "applyExtensions" description in the docs

### ISSUE THREAD

**Issue by fabiospampinato** [tinyhttp/tinyhttp#287] opened 2021-07-07 17:18 UTC
**Describe the bug**

If I do the following the app just hangs:

```ts
const app = new App ({
  applyExtensions: (req, res, next) => {}
});
```

If I do the following routes are being called (so it seems that I need to call `next`, the docs say otherwise):

```ts
const app = new App ({
  applyExtensions: (req, res, next) => {
    next ();
  }
});
```

But then I'm getting this error:

```
TypeError: t.json is not a function
    at /Users/fabio/Projects/notable-website/dist/download/index.js:1:3286
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/fabio/Projects/notable-website/node_modules/@tinyhttp/app/dist/index.cjs:142:13
    at async /Users/fabio/Projects/notable-website/node_modules/@tinyhttp/app/dist/index.cjs:353:13
```

So all custom extensions got disabled it seems?

I've no idea how I am supposed to actually extend these objects now, extending something shouldn't disable anything by default IMO.

**Expected behavior**

It should just work.

**Versions**

- `node`: 12.12.0
- `@tinyhttp/app`: latest

**Comment by talentlessguy** [comment] 2021-07-07 17:41
actually it's not a bug... the docs are wrong...

`applyExtensions` doesn't extend current handlers, it initializes them. Sorry for confusion, will fix that right now

**Comment by talentlessguy** [comment] 2021-07-07 17:49
fixed with https://github.com/tinyhttp/website/commit/10de809bf6f7ef7e0beb5340072e5534a50d2013

in short, do this instead:

```js
import { App, extendMiddleware } from '@tinyhttp/app'

const app = new App({
  applyExtensions: (req, res, next) => {
    extendMiddleware(req, res, next)

    res.someExt = someExt(req, res, next)
  }
})
```

**Closed by talentlessguy** 2021-07-07 17:49 UTC
Labels: docs
