### ISSUE TITLE
Server instance (of `@tinyhttp/app`) hangs on test since 2.0.33

### ISSUE THREAD

**Issue by aldy505** [tinyhttp/tinyhttp#410] opened 2023-10-01 05:25 UTC
**Describe the bug**

Like usual, I was maintaining [malibu](https://github.com/tinyhttp/malibu), bumping the dependencies. I ran `pnpm run test`, and got it hanging on me. At first I thought it's a problem with uvu, yet uvu is not updated. Then I thought it's a problem with Typescript -- since I upgraded a major version from v4 to v5. When I downgraded just Typescript from v5 to v4 (v4.9.5 exactly), it.. still hangs. I also thought it's a problem with the Node version I was using (v20), downgraded to (v18) and it still hangs.

Then, I downgraded `@tinyhttp/app` back to `2.0.29` from `2.2.0`, and the test got passed without even hanging. I trace the version one by one, and got the hanging problem since `2.0.33`.

Saw the diff between `2.0.29` and `2.2.0`, didn't think there's something that's causing the issue. See [the diff here](https://github.com/tinyhttp/tinyhttp/compare/a4a12e8809e3a5baeca98158d8812da46630b24a..196bc9a6c1ffa9f63ecfdfffa2b101d2f4b62d58).

**To Reproduce**

See my PR on malibu here: https://github.com/tinyhttp/malibu/pull/5

**Expected behavior**

It's not supposed to be hanging.

**Versions**

- `node`: 18, 20
- `@tinyhttp/app`: 2.0.33

**Additional context**

**Comment by talentlessguy** [comment] 2023-10-08 12:52
@aldy505 could you please write out a minimal reproduction for the hanging?

**Comment by aldy505** [comment] 2023-10-09 02:39
> @aldy505 could you please write out a minimal reproduction for the hanging? (a code snippet)

Will do later this weekend (or the next 2 weekend)

**Comment by aarontravass** [comment] 2023-12-18 00:01
@aldy505 any updates?

**Comment by aldy505** [comment] 2023-12-19 00:55
> @aldy505 any updates?

@aarontravass not yet, I'm occupied with work until early January.

**Comment by talentlessguy** [comment] 2024-09-12 11:38
@aldy505 is the issue still relevant?

**Comment by aldy505** [comment] 2024-09-12 11:45
> @aldy505 is the issue still relevant?

haven't gotten around this

**Comment by aldy505** [comment] 2024-09-15 11:33
Alright, finally got time.

Here's the repro: https://github.com/aldy505/tinyhttp-app-hangs-repro

It turns out I need to **manually** close the `server` instance, which is weird since on the previous tinyhttp version, I don't need to do that.

Feel free to close this issue if you guys think this is not relevant for normal people.

**Comment by talentlessguy** [comment] 2024-09-15 11:45
I'm not sure if this is related to tinyhttp and not something else tbh

I'll close it since it doesn't happen elsewhere

**Closed by talentlessguy** 2024-09-15 11:45 UTC
Labels: bug, help wanted, needs reproduction

**Comment by talentlessguy** [comment] 2024-09-15 11:46
it might hang because host is undefined and not 0.0.0.0 by default
